version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    environment:
      TAG: darklang/dark-base
    steps:
      - checkout
      - run: echo "Building images for version $(./tag-version.sh)."
      - run: docker build --target dark-base -t $TAG:$(./tag-version.sh) .
      - deploy:
          name: Push image
          command: |
            docker login --username pbiggar --password "${DOCKER_HUB_TOKEN}"
            docker push $TAG:$(./tag-version.sh)


